// Tests for the Vasicek model: closed forms, bond options (parity, sigma=0
// degeneration), exact-transition Monte Carlo, and calibration.

#include "irm/vasicek.hpp"

#include <cmath>
#include <stdexcept>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "irm/quotes.hpp"

namespace {

const std::string kDataDir = IRM_DATA_DIR;

TEST(Vasicek, ParameterValidation) {
    EXPECT_THROW(irm::Vasicek(0.0, 0.03, 0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(-0.5, 0.03, 0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(0.5, 0.03, -0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(0.5, std::nan(""), 0.01, 0.02), std::invalid_argument);
    EXPECT_NO_THROW(irm::Vasicek(0.5, 0.03, 0.0, -0.02));  // sigma=0, r0<0 legal
}

TEST(Vasicek, ZcbClosedFormMatchesDirectFormula) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    const double tau = 5.0;
    const double b = (1.0 - std::exp(-0.5 * tau)) / 0.5;
    const double a = std::exp((0.03 - 0.0001 / (2.0 * 0.25)) * (b - tau) -
                              0.0001 * b * b / (4.0 * 0.5));
    EXPECT_NEAR(m.zcb_price(tau), a * std::exp(-b * 0.02), 1e-15);
    EXPECT_NEAR(m.zero_yield(tau), -std::log(m.zcb_price(tau)) / tau, 1e-15);
    EXPECT_THROW(m.zcb_price(1.0, 2.0), std::invalid_argument);
    EXPECT_THROW(m.zero_yield(1.0, 1.0), std::invalid_argument);
}

TEST(Vasicek, RtMomentsAndLongHorizonLimits) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_NEAR(m.r_mean(0.0), 0.02, 1e-16);
    EXPECT_NEAR(m.r_var(0.0), 0.0, 1e-16);
    // Long-horizon limits: mean -> theta, var -> sigma^2/(2 kappa).
    EXPECT_NEAR(m.r_mean(200.0), 0.03, 1e-12);
    EXPECT_NEAR(m.r_var(200.0), 0.0001 / 1.0, 1e-12);
    EXPECT_THROW(m.r_mean(-1.0), std::invalid_argument);
    EXPECT_THROW(m.r_var(-1.0), std::invalid_argument);
}

TEST(Vasicek, BondOptionPutCallParity) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    // ZBC - ZBP = P(0,S) - K P(0,T) across a strike grid (property check).
    for (double k = 0.85; k <= 1.05; k += 0.02) {
        const double lhs = m.zbc(1.0, 3.0, k) - m.zbp(1.0, 3.0, k);
        const double rhs = m.zcb_price(3.0) - k * m.zcb_price(1.0);
        EXPECT_NEAR(lhs, rhs, 1e-14) << "strike " << k;
    }
}

TEST(Vasicek, BondOptionValidationAndDegenerate) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_THROW(m.zbc(1.0, 3.0, 0.0), std::invalid_argument);
    EXPECT_THROW(m.zbc(1.0, 3.0, -0.5), std::invalid_argument);
    EXPECT_THROW(m.zbc(3.0, 1.0, 0.9), std::invalid_argument);
    EXPECT_THROW(m.zbc(-1.0, 3.0, 0.9), std::invalid_argument);
    // sigma = 0: intrinsic on the forward bond.
    const irm::Vasicek det(0.5, 0.03, 0.0, 0.02);
    const double intrinsic = det.zcb_price(3.0) - 0.9 * det.zcb_price(1.0);
    EXPECT_NEAR(det.zbc(1.0, 3.0, 0.9), std::max(intrinsic, 0.0), 1e-15);
    EXPECT_NEAR(det.zbp(1.0, 3.0, 0.9), std::max(-intrinsic, 0.0), 1e-15);
    // S = T also degenerates (sigma_p = 0), option on an expiring bond.
    EXPECT_NEAR(m.zbc(2.0, 2.0, 0.9), (1.0 - 0.9) * m.zcb_price(2.0), 1e-15);
}

TEST(Vasicek, NegativeRatesSupported) {
    const irm::Vasicek m(0.3, 0.01, 0.008, -0.005);
    // Short-maturity ZCB with negative r0 prices above 1.
    EXPECT_GT(m.zcb_price(0.5), 1.0);
    EXPECT_LT(m.zero_yield(0.5), 0.0);
}

TEST(Vasicek, McZcbWithin3StandardErrors) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    const auto [price, se] = m.mc_zcb(5.0, /*n_steps=*/8, /*n_paths=*/50000, /*seed=*/1234);
    EXPECT_GT(se, 0.0);
    EXPECT_NEAR(price, m.zcb_price(5.0), 3.0 * se);
}

TEST(Vasicek, McSigmaZeroIsDeterministic) {
    const irm::Vasicek det(0.5, 0.03, 0.0, 0.02);
    const auto [price, se] = det.mc_zcb(5.0, 8, 100, 1);
    EXPECT_EQ(se, 0.0);
    EXPECT_NEAR(price, det.zcb_price(5.0), 1e-12);
}

TEST(Vasicek, SimulateValidation) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_THROW(m.simulate(0.0, 8, 10, 1), std::invalid_argument);
    EXPECT_THROW(m.simulate(1.0, 0, 10, 1), std::invalid_argument);
    EXPECT_THROW(m.simulate(1.0, 8, 0, 1), std::invalid_argument);
}

TEST(VasicekCalibration, RecoversCleanParameters) {
    // Yields generated by a known model must be recovered near-exactly.
    const irm::Vasicek truth(0.8, 0.05, 0.02, 0.03);
    std::vector<double> ts, ys;
    for (double t : {0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 15.0, 20.0}) {
        ts.push_back(t);
        ys.push_back(truth.zero_yield(t));
    }
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03);
    EXPECT_TRUE(cal.converged);
    EXPECT_NEAR(cal.kappa, 0.8, 1e-3);
    EXPECT_NEAR(cal.theta, 0.05, 1e-4);
    EXPECT_NEAR(cal.sigma, 0.02, 1e-3);
    EXPECT_LT(cal.rmse, 1e-8);
}

TEST(VasicekCalibration, FitsBundledNoisyYields) {
    const auto [ts, ys] = irm::load_zero_yields(kDataDir + "/zero_yields.csv");
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03);
    EXPECT_TRUE(cal.converged);
    // Noise is N(0, 2e-5); the fit should be at that scale.
    EXPECT_LT(cal.rmse, 1e-4);
    EXPECT_NEAR(cal.kappa, 0.8, 0.2);
    EXPECT_NEAR(cal.theta, 0.05, 0.01);
    EXPECT_GE(cal.sigma, 0.0);
    EXPECT_NO_THROW(cal.model());
}

TEST(VasicekCalibration, InputValidation) {
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0}, {0.03, 0.04}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, 0.04}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, -2.0, 3.0}, {0.03, 0.04, 0.05}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, std::nan(""), 0.05}, 0.03),
                 std::invalid_argument);
}

}  // namespace
