// Tests for the Vasicek model: closed forms, bond options (parity, sigma=0
// degeneration), exact-transition Monte Carlo, and calibration.

#include "irm/vasicek.hpp"

#include <cmath>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "irm/quotes.hpp"

namespace {

const std::string kDataDir = IRM_DATA_DIR;

TEST(Vasicek, ParameterValidation) {
    EXPECT_THROW(irm::Vasicek(0.0, 0.03, 0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(-0.5, 0.03, 0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(0.5, 0.03, -0.01, 0.02), std::invalid_argument);
    EXPECT_THROW(irm::Vasicek(0.5, std::nan(""), 0.01, 0.02), std::invalid_argument);
    EXPECT_NO_THROW(irm::Vasicek(0.5, 0.03, 0.0, -0.02));  // sigma=0, r0<0 legal
}

TEST(Vasicek, ZcbClosedFormMatchesDirectFormula) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    const double tau = 5.0;
    const double b = (1.0 - std::exp(-0.5 * tau)) / 0.5;
    const double a = std::exp((0.03 - 0.0001 / (2.0 * 0.25)) * (b - tau) -
                              0.0001 * b * b / (4.0 * 0.5));
    EXPECT_NEAR(m.zcb_price(tau), a * std::exp(-b * 0.02), 1e-15);
    EXPECT_NEAR(m.zero_yield(tau), -std::log(m.zcb_price(tau)) / tau, 1e-15);
    EXPECT_THROW(m.zcb_price(1.0, 2.0), std::invalid_argument);
    EXPECT_THROW(m.zero_yield(1.0, 1.0), std::invalid_argument);
}

TEST(Vasicek, RtMomentsAndLongHorizonLimits) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_NEAR(m.r_mean(0.0), 0.02, 1e-16);
    EXPECT_NEAR(m.r_var(0.0), 0.0, 1e-16);
    // Long-horizon limits: mean -> theta, var -> sigma^2/(2 kappa).
    EXPECT_NEAR(m.r_mean(200.0), 0.03, 1e-12);
    EXPECT_NEAR(m.r_var(200.0), 0.0001 / 1.0, 1e-12);
    EXPECT_THROW(m.r_mean(-1.0), std::invalid_argument);
    EXPECT_THROW(m.r_var(-1.0), std::invalid_argument);
}

TEST(Vasicek, BondOptionPutCallParity) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    // ZBC - ZBP = P(0,S) - K P(0,T) across a strike grid (property check).
    for (double k = 0.85; k <= 1.05; k += 0.02) {
        const double lhs = m.zbc(1.0, 3.0, k) - m.zbp(1.0, 3.0, k);
        const double rhs = m.zcb_price(3.0) - k * m.zcb_price(1.0);
        EXPECT_NEAR(lhs, rhs, 1e-14) << "strike " << k;
    }
}

TEST(Vasicek, BondOptionValidationAndDegenerate) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_THROW(m.zbc(1.0, 3.0, 0.0), std::invalid_argument);
    EXPECT_THROW(m.zbc(1.0, 3.0, -0.5), std::invalid_argument);
    EXPECT_THROW(m.zbc(3.0, 1.0, 0.9), std::invalid_argument);
    EXPECT_THROW(m.zbc(-1.0, 3.0, 0.9), std::invalid_argument);
    // sigma = 0: intrinsic on the forward bond.
    const irm::Vasicek det(0.5, 0.03, 0.0, 0.02);
    const double intrinsic = det.zcb_price(3.0) - 0.9 * det.zcb_price(1.0);
    EXPECT_NEAR(det.zbc(1.0, 3.0, 0.9), std::max(intrinsic, 0.0), 1e-15);
    EXPECT_NEAR(det.zbp(1.0, 3.0, 0.9), std::max(-intrinsic, 0.0), 1e-15);
    // S = T also degenerates (sigma_p = 0), option on an expiring bond.
    EXPECT_NEAR(m.zbc(2.0, 2.0, 0.9), (1.0 - 0.9) * m.zcb_price(2.0), 1e-15);
}

TEST(Vasicek, NegativeRatesSupported) {
    const irm::Vasicek m(0.3, 0.01, 0.008, -0.005);
    // Short-maturity ZCB with negative r0 prices above 1.
    EXPECT_GT(m.zcb_price(0.5), 1.0);
    EXPECT_LT(m.zero_yield(0.5), 0.0);
}

TEST(Vasicek, McZcbWithin3StandardErrors) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    const auto [price, se] = m.mc_zcb(5.0, /*n_steps=*/8, /*n_paths=*/50000, /*seed=*/1234);
    EXPECT_GT(se, 0.0);
    EXPECT_NEAR(price, m.zcb_price(5.0), 3.0 * se);
}

TEST(Vasicek, McSigmaZeroIsDeterministic) {
    const irm::Vasicek det(0.5, 0.03, 0.0, 0.02);
    const auto [price, se] = det.mc_zcb(5.0, 8, 100, 1);
    EXPECT_EQ(se, 0.0);
    EXPECT_NEAR(price, det.zcb_price(5.0), 1e-12);
}

TEST(Vasicek, SimulateValidation) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_THROW(m.simulate(0.0, 8, 10, 1), std::invalid_argument);
    EXPECT_THROW(m.simulate(1.0, 0, 10, 1), std::invalid_argument);
    EXPECT_THROW(m.simulate(1.0, 8, 0, 1), std::invalid_argument);
}

TEST(VasicekCalibration, RecoversCleanParameters) {
    // Yields generated by a known model must be recovered near-exactly.
    const irm::Vasicek truth(0.8, 0.05, 0.02, 0.03);
    std::vector<double> ts, ys;
    for (double t : {0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 15.0, 20.0}) {
        ts.push_back(t);
        ys.push_back(truth.zero_yield(t));
    }
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03);
    EXPECT_TRUE(cal.converged);
    EXPECT_FALSE(cal.at_bound);
    EXPECT_EQ(cal.n_starts, 3);
    EXPECT_FALSE(cal.sigma_fixed);
    EXPECT_NEAR(cal.kappa, 0.8, 1e-3);
    EXPECT_NEAR(cal.theta, 0.05, 1e-4);
    EXPECT_NEAR(cal.sigma, 0.02, 1e-3);
    EXPECT_LT(cal.rmse, 1e-8);
}

TEST(VasicekCalibration, MultistartReportsNonIdentifiability) {
    // The bundled noisy yields have two least-squares minima with rmse within
    // 2 % of each other, at (0.80, 0.050, 0.023) and (0.41, 0.069, 0.080):
    // the diagnostics must say so instead of claiming a unique fit.
    const auto [ts, ys] = irm::load_zero_yields(kDataDir + "/zero_yields.csv");
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03);
    EXPECT_TRUE(cal.converged);
    EXPECT_FALSE(cal.at_bound);
    EXPECT_LT(cal.rmse, 2e-5);
    EXPECT_EQ(cal.n_starts, 3);
    EXPECT_FALSE(cal.identified);
    EXPECT_GT(cal.sigma_spread, 0.01);
    EXPECT_GT(cal.kappa_spread, 0.1);
    EXPECT_GE(cal.theta, 0.04);
    EXPECT_LE(cal.theta, 0.07);
    EXPECT_NO_THROW(cal.model());
    // Two warm starts land on the two minima with equivalent rmse.
    double mean_y = 0.0;
    for (double y : ys) mean_y += y;
    mean_y /= static_cast<double>(ys.size());
    const auto a = irm::calibrate_vasicek(ts, ys, 0.03, std::vector<double>{0.5, mean_y, 0.01});
    const auto b = irm::calibrate_vasicek(ts, ys, 0.03, std::vector<double>{0.5, 0.05, 0.05});
    EXPECT_EQ(a.n_starts, 1);
    EXPECT_LT(a.rmse, 2e-5);
    EXPECT_LT(b.rmse, 2e-5);
    EXPECT_LT(std::fabs(a.rmse - b.rmse), 5e-6);
    EXPECT_GT(std::fabs(a.sigma - b.sigma), 0.01);
    EXPECT_FALSE(a.identified);  // single start: identifiability not assessed
}

TEST(VasicekCalibration, SigmaFixedIdentifiesKappaTheta) {
    const auto [ts, ys] = irm::load_zero_yields(kDataDir + "/zero_yields.csv");
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03, std::nullopt, 4000, 0.02);
    EXPECT_TRUE(cal.sigma_fixed);
    EXPECT_EQ(cal.sigma, 0.02);
    EXPECT_TRUE(cal.converged);
    EXPECT_TRUE(cal.identified);
    EXPECT_FALSE(cal.at_bound);
    EXPECT_NEAR(cal.kappa, 0.8002161, 1e-6);
    EXPECT_NEAR(cal.theta, 0.0499880, 1e-6);
    EXPECT_LT(cal.kappa_spread, 1e-6);
    EXPECT_EQ(cal.sigma_spread, 0.0);
    // sigma_fixed with a warm start ignores x0[2].
    const auto warm =
        irm::calibrate_vasicek(ts, ys, 0.03, std::vector<double>{0.3, 0.04, 99.0}, 4000, 0.02);
    EXPECT_NEAR(warm.kappa, cal.kappa, 1e-6);
    EXPECT_EQ(warm.sigma, 0.02);
    EXPECT_THROW(irm::calibrate_vasicek(ts, ys, 0.03, std::nullopt, 4000, -0.01),
                 std::invalid_argument);
}

TEST(VasicekCalibration, PenaltyStartNotReportedConverged) {
    const auto [ts, ys] = irm::load_zero_yields(kDataDir + "/zero_yields.csv");
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03, std::vector<double>{-1.0, 0.0, -1.0});
    EXPECT_TRUE(cal.at_bound);
    EXPECT_FALSE(cal.converged);  // stopped at the penalty wall
    EXPECT_LE(cal.kappa, 1e-5);
    EXPECT_TRUE(std::isfinite(cal.rmse));
}

TEST(VasicekCalibration, FlatYieldsSigmaAtZeroBound) {
    // Flat yields equal to r0 are fitted exactly by sigma = 0, theta = r0 for
    // any kappa: sigma sits on its bound and kappa is not identified.
    const std::vector<double> ts = {1.0, 2.0, 3.0, 5.0, 10.0};
    const std::vector<double> ys(5, 0.03);
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03);
    EXPECT_TRUE(cal.at_bound);
    EXPECT_FALSE(cal.converged);
    EXPECT_LT(cal.sigma, 1e-5);
    EXPECT_NEAR(cal.theta, 0.03, 1e-8);
    EXPECT_FALSE(cal.identified);
}

TEST(VasicekCalibration, NonConvergenceReportedNotThrown) {
    const irm::Vasicek truth(0.8, 0.05, 0.02, 0.03);
    std::vector<double> ts = {1.0, 2.0, 5.0, 10.0}, ys;
    for (double t : ts) ys.push_back(truth.zero_yield(t));
    const auto cal = irm::calibrate_vasicek(ts, ys, 0.03, std::nullopt, /*maxiter=*/2);
    EXPECT_FALSE(cal.converged);
    EXPECT_EQ(cal.iterations, 2);
    EXPECT_TRUE(std::isfinite(cal.rmse));
}

TEST(VasicekCalibration, InputValidation) {
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0}, {0.03, 0.04}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, 0.04}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, -2.0, 3.0}, {0.03, 0.04, 0.05}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, std::nan(""), 0.05}, 0.03),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, 0.04, 0.05},
                                        std::numeric_limits<double>::infinity()),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek({1.0, 2.0, 3.0}, {0.03, 0.04, 0.05}, 0.03, std::nullopt,
                                        /*maxiter=*/0),
                 std::invalid_argument);
}

TEST(VasicekCalibration, X0WrongLengthOrNonFiniteRejected) {
    const std::vector<double> ts = {1.0, 2.0, 3.0}, ys = {0.02, 0.021, 0.022};
    // A 2-entry x0 used to read p[2] past the end (undefined behaviour).
    EXPECT_THROW(irm::calibrate_vasicek(ts, ys, 0.02, std::vector<double>{0.5, 0.03}),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek(ts, ys, 0.02, std::vector<double>{0.5, 0.03, 0.01, 0.0}),
                 std::invalid_argument);
    EXPECT_THROW(irm::calibrate_vasicek(ts, ys, 0.02, std::vector<double>{0.5, std::nan(""), 0.01}),
                 std::invalid_argument);
}

TEST(Vasicek, McZcbManySmallStepsUnbiased) {
    // kappa*dt = 2.5e-6 per step: the naive var_i would be wrong by orders of
    // magnitude; with the series the estimator stays unbiased.
    const irm::Vasicek m(1e-3, 0.03, 0.01, 0.02);
    const double analytic = m.zcb_price(5.0);
    const auto [price, se] = m.mc_zcb(5.0, /*n_steps=*/2000, /*n_paths=*/10000, /*seed=*/77);
    EXPECT_GT(se, 0.0);
    EXPECT_NEAR(price, analytic, 3.0 * se);
}

TEST(Vasicek, SameSeedSameResultAndSinglePath) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    const auto a = m.mc_zcb(3.0, 4, 2000, 11);
    const auto b = m.mc_zcb(3.0, 4, 2000, 11);
    const auto c = m.mc_zcb(3.0, 4, 2000, 12);
    EXPECT_EQ(a.first, b.first);
    EXPECT_EQ(a.second, b.second);
    EXPECT_NE(a.first, c.first);
    const auto single = m.mc_zcb(1.0, 1, 1, 5);
    EXPECT_TRUE(std::isfinite(single.first));
    EXPECT_GT(single.first, 0.0);
    EXPECT_EQ(single.second, 0.0);
}

TEST(Vasicek, NonFiniteAndOverflowRejected) {
    const irm::Vasicek m(0.5, 0.03, 0.01, 0.02);
    EXPECT_THROW(m.zcb_price(std::nan("")), std::invalid_argument);
    EXPECT_THROW(m.zcb_price(5.0, 0.0, std::numeric_limits<double>::infinity()),
                 std::invalid_argument);
    EXPECT_THROW(m.r_mean(1.0, std::nan("")), std::invalid_argument);
    EXPECT_THROW(m.zero_yield(std::numeric_limits<double>::infinity()), std::invalid_argument);
    EXPECT_THROW(m.zcb_price(5.0, 0.0, -1e6), std::invalid_argument);  // exp overflow
}

}  // namespace
